#
# File    MWParser.py
#
# Brief   Wrapper/helper functions for the Cognex Barcode Scanner Parser Add-ons
# 
# Details This class is a companion to MWB and MWResult, the main interface to the 
#         Cognex Mobile Barcode SDK. Since the parsing functions are not used in all
#         applications, this interface class has been separated. Note though that the 
#         actual implementation is part of the same libary (BarcodeScanner.dll or
#         libBarcodeScanner.so).
#         
# Notice  Copyright (C) Cognex Corporation 
#
#


# Basic return values from functions
MWP_RT_OK = 0
MWP_RT_FAIL = -1
MWP_RT_NOT_SUPPORTED = -2
MWP_RT_BAD_PARAM = -3
MWP_RT_BAD_INPUT = -4

# Parser types
MWP_PARSER_MASK_NONE = 0x00000000
MWP_PARSER_MASK_GS1 = 0x00000001
MWP_PARSER_MASK_IUID = 0x00000002
MWP_PARSER_MASK_ISBT = 0x00000004
MWP_PARSER_MASK_AAMVA = 0x00000008
MWP_PARSER_MASK_HIBC = 0x00000010
MWP_PARSER_MASK_SCM = 0x00000020

# UID PARSER ERROR CODES
UID_ERROR_INVALID_HEADER = -1.0
UID_ERROR_INVALID_FORMAT = -2.0
UID_ERROR_INVALID_EI = -3.0
UID_ERROR_INVALID_CAGE = -3.1
UID_ERROR_INVALID_DUNS = -3.2
UID_ERROR_INVALID_DODAAC = -3.3
UID_ERROR_INVALID_GS1COMP = -3.4
UID_ERROR_INVALID_PN = -4.0
UID_ERROR_INVALID_SN = -5.0
UID_ERROR_INVALID_UII = -6.0
UID_ERROR_INVALID_LOT = -7.0
UID_ERROR_GS_MISSING = -8.0    # GS Missing after Header
UID_ERROR_RS_MISSING = -9.0
UID_ERROR_EOT_MISSING = -10.0
UID_ERROR_NO_SN = -11.0
UID_ERROR_NO_EI = -12.0
UID_ERROR_NO_PN = -13.0
UID_ERROR_NO_LOT = -14
UID_ERROR_DUPLICATE_DQ = -15
UID_ERROR_DUPLICATE_UII = -16
UID_ERROR_DUPLICATE_LOT = -17
UID_ERROR_DUPLICATE_SN = -18
UID_ERROR_DUPLICATE_EI = -19
UID_ERROR_LOT_PN_CONFLICT = -20
UID_ERROR_MISSING_REQ = -21
UID_ERROR_INVALID_IAC = -22
UID_ERROR_INVALID_TEI = -23
UID_ERROR_NOT_ENOUGHT_MEMORY = -24


# UID PARSER WARNING CODES
UID_WARN_EXTRA_CHARS = 91      # characters after EOT
UID_WARN_UNNEEDED_DATA = 92    # unneeded additional data
UID_WARN_SPACE_AROUND = 93     # space at the beginning or end of the uid
UID_WARN_UNKNOWN_DQ = 94
UID_WARN_OBSOLETE_FORMAT = 95  # warning for DD


# AAMVA PARSER ERROR CODES
AAMVA_ERROR_INVALID_FORMAT = -1
AAMVA_ERROR_INVALID_HEADER = -2
AAMVA_ERROR_INVALID_IIN = -3
NOT_ENOUGHT_MEMORY = -4
AAMVA_ERROR_INVALID_JN = -5
AAMVA_ERROR_INVALID_NENTIRES = -6


# AAMVA PARSER WARNING CODES
AAMVA_WARNING_MISSING_MANDATORY_FIELDS = 1


# UPS (SCM) PARSER ERROR CODES
SCM_ERROR_INVALID_FORMAT = -1
SCM_ERROR_INVALID_CODE = -2
SCM_ERROR_ELEMENT_NOT_FOUND = -3
SCM_ERROR_CANT_ALLOCATE_MEMORY = -4

# UPS (SCM) PARSER WARNING CODES
SCM_WARNING_LENGTH_OUT_OF_BOUNDS = 1	  # possible compression used by UPS
SCM_WARNING_FIELD_EXCEEDS_MAX_LENGTH = 2  # possible compression used by UPS
SCM_WARNING_INVALID_TERMINATOR = 3        # possible compression used by UPS

